/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class MainPage extends javax.swing.JFrame {
  
 public static String cat;
    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        
         try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            System.out.println("connected");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","java");
            System.out.println("connected");
            String query="select CAT from CATAGRORIES";
            PreparedStatement ps=con.prepareStatement(query);
            ResultSet  rs=ps.executeQuery();
           
             while(rs.next())
              {
              
                cb.addItem(rs.getString("CAT"));
               
              }
             
        }
          catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e); 
        }
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        cb = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        Submit = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb.setBackground(new java.awt.Color(153, 51, 0));
        cb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb.setForeground(new java.awt.Color(153, 51, 0));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        getContentPane().add(cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 148, 45));

        jLabel1.setBackground(new java.awt.Color(153, 51, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText(" QUIZ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 180, 70));

        Submit.setBackground(new java.awt.Color(153, 51, 0));
        Submit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 510, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\Final.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(640, 570));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        
                         
       
        
        
    }                                  
 
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
       
       cat=(String) cb.getSelectedItem();
       
      /*ArrayList<Display> displaylist=new ArrayList<Display>();   
       try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            System.out.println("connected");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","java");
            System.out.println("connected");
           
            System.out.println(cat);
            
              String query="select * from QUEST WHERE CAT='"+cat+"'";
            PreparedStatement ps=con.prepareStatement(query);
            ResultSet  rs=ps.executeQuery();
          
         
        
           while(rs.next())
              {
               
              
                  
                  Display d=new  Display();
                  d.setQuestion(rs.getString("QUES"));
                  d.setOption1(rs.getString("OP_1"));
                  d.setOption2(rs.getString("OP_2"));
                  d.setOption3(rs.getString("OP_3"));
                  d.setOption4(rs.getString("OP_4"));
                  displaylist.add(d);
                  
             
                }
           
        
       }
          catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e); 
        }*/
          QuesDisplay w=new  QuesDisplay();
         w.setVisible(true);
         dispose();
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton Submit;
    private javax.swing.JComboBox cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration                   

    
    
    
    
    
}
