/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Loginbutton = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        UserNmaetextfield = new javax.swing.JTextField();
        Passwordtextfield = new javax.swing.JPasswordField();
        Cancelbutton = new javax.swing.JToggleButton();
        Enterbutton = new javax.swing.JToggleButton();
        Forgetpassword = new javax.swing.JToggleButton();
        Password = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Loginbutton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Loginbutton.setForeground(new java.awt.Color(153, 51, 0));
        Loginbutton.setText("LOGIN");
        jPanel1.add(Loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 180, 50));

        UserName.setBackground(new java.awt.Color(153, 51, 0));
        UserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UserName.setText("Enter UserName");
        jPanel1.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 210, 29));

        UserNmaetextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNmaetextfieldActionPerformed(evt);
            }
        });
        jPanel1.add(UserNmaetextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 199, 310, 30));

        Passwordtextfield.setText("jPasswordField1");
        Passwordtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordtextfieldActionPerformed(evt);
            }
        });
        jPanel1.add(Passwordtextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 339, 310, 30));

        Cancelbutton.setBackground(new java.awt.Color(153, 51, 0));
        Cancelbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Cancelbutton.setText("CANCEL");
        Cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));

        Enterbutton.setBackground(new java.awt.Color(153, 51, 0));
        Enterbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Enterbutton.setText("ENTER");
        Enterbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Enterbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, -1, -1));

        Forgetpassword.setBackground(new java.awt.Color(153, 51, 0));
        Forgetpassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Forgetpassword.setText("FORGET PASSWORD");
        Forgetpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgetpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Forgetpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, -1, -1));

        Password.setBackground(new java.awt.Color(153, 51, 0));
        Password.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Password.setText("Enter Password");
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 200, 29));

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Create An Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\Final.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(640, 570));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void EnterbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
         String password =Passwordtextfield.getText();
        String username =UserNmaetextfield.getText();
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            System.out.println("connected");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","java");
            System.out.println("connected");
            String query="Select USERNAME,PASSWORD from SIGNIN1 where USERNAME='"+username+"'and PASSWORD ='"+password+"'";
            PreparedStatement ps=con.prepareStatement(query);
            ResultSet  rs=ps.executeQuery();
           
            int count =0;
              while(rs.next())
              {
                 count =count+1;
              }
               if(count==1)
            {
               // JOptionPane.showMessageDialog(null,"Login Successfully");
                MainPage w=new MainPage();
                  w.setVisible(true);
                   
            }
              // else if(count>1)
           // {
                //JOptionPane.showMessageDialog(null,"Login Failed.Duplicate Please try again....");
                
           // }
                 else
            {
                JOptionPane.showMessageDialog(null,"Login Failed.Please try again....");
                LOGIN a=new LOGIN();
                a.setVisible(true);
            }
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e); 
        }
     
       /* if(password.contains("admin123")&&username.contains("admin"))
        {
            UserNametextfield.setText("  ");
            Passwordtextfield.setText("  ");
            close();
            Welcome w=new Welcome();
            w.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"This password is Extremely wronge !\n Click OK  and try again .2","Wronge Pass",JOptionPane.ERROR_MESSAGE);
            Passwordtextfield.setText(" ");
            UserNametextfield.setText(" ");
        }*/
      dispose();
        
    }                                           

    private void ForgetpasswordActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        SIGNIN s=new SIGNIN();
        s.setVisible(true);  
        dispose();
    }                                              

    private void CancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
         close();
    }                                            

    private void UserNmaetextfieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void PasswordtextfieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        SIGNIN a=new SIGNIN();
         a.setVisible(true);
         dispose();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton Cancelbutton;
    private javax.swing.JToggleButton Enterbutton;
    private javax.swing.JToggleButton Forgetpassword;
    private javax.swing.JLabel Loginbutton;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField Passwordtextfield;
    private javax.swing.JLabel UserName;
    private javax.swing.JTextField UserNmaetextfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
 private void close()
    {
    WindowEvent winclosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclosing);
  

    
}
}
