/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import com.sun.javafx.scene.control.SelectedCellsMap;
import java.nio.channels.SelectionKey;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import static javaapplication4.MainPage.cat;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class QuesDisplay extends javax.swing.JFrame {
String s1,s,radioText;
public static ArrayList A=new ArrayList();      
public static ArrayList B=new ArrayList(); 
public static ArrayList C=new ArrayList(); 
public static String Currect_Question,Select_Answer,Correct_Answer;
int i=0;
public static int m;
public static int number=0;
ResultSet rs;
ArrayList<Display> displaylist=new ArrayList<Display>();
 public void Table()
      {
          
      if(i<=m)
      {
      
      //  System.out.print(i+"  "+m);
           // System.out.println(displaylist.get(i).getQuestion());
             
               jLabel1.setText(displaylist.get(i).getQuestion());
                Button1.setText(displaylist.get(i).getOption1());
                Button2.setText(displaylist.get(i).getOption2());
                Button3.setText(displaylist.get(i).getOption3());
                Button4.setText(displaylist.get(i).getOption4());
                Correct_Answer=displaylist.get(i).getCorrect();
             //   Currect_Question=displaylist.get(i).getQuestion();
               // System.out.println(a);
                
                 Button1.setSelected(false);
                 Button2.setSelected(false);
                 Button3.setSelected(false);
                 Button4.setSelected(false);
                
                
              
      }    
     else
      {
           Result r=new Result();
          r.setVisible(true);
          dispose();
      }
     }

    /**
     * Creates new form QuesDisplay
     */
    public QuesDisplay() {
        initComponents();
  s=  MainPage.cat;
      System.out.println(s);
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            System.out.println("connected");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","java");
            System.out.println("connected");
           
            System.out.println(cat); 
            
              String query="select * from QUEST WHERE CAT='"+cat+"'";
            PreparedStatement ps=con.prepareStatement(query);
                rs=ps.executeQuery();
     while(rs.next())
              {
                  m=displaylist.size();
                  Display d=new  Display();
                  d.setQuestion(rs.getString("QUES"));
                  d.setOption1(rs.getString("OP_1"));
                  d.setOption2(rs.getString("OP_2"));
                  d.setOption3(rs.getString("OP_3"));
                  d.setOption4(rs.getString("OP_4"));
                  d.setCorrect(rs.getString("CORRECT"));
                  // System.out.println(rs.getString("QUES"));
         Currect_Question=rs.getString("QUES");
                 // System.out.println(Currect_Question);
                  displaylist.add(d);
              
              
              }
     Table();
        
        } 
          catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e); 
        }
        finally{
            //Table();
        }
     
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Button4 = new javax.swing.JRadioButton();
        Button2 = new javax.swing.JRadioButton();
        Button1 = new javax.swing.JRadioButton();
        Button3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });
        jPanel1.add(Button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 478, -1));

        Button2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        jPanel1.add(Button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 478, -1));

        Button1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        jPanel1.add(Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 478, -1));

        Button3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        jPanel1.add(Button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 478, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 67, 670, 25));

        Next.setBackground(new java.awt.Color(153, 51, 0));
        Next.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Next.setText("NEXT");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        jPanel1.add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 490, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\Final.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 570));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {                                     
        
      
   
      if(Button1.isSelected())
        {
          Button2.setSelected(false);
          Button3.setSelected(false);
          Button4.setSelected(false); 
            radioText = Button1.getText();
        }
      else
          { 
              if(Button2.isSelected())
              {
          Button1.setSelected(false);
          Button3.setSelected(false);
          Button4.setSelected(false); 
           radioText = Button2.getText();
              }
            else
              {
                if(Button3.isSelected())
                  {
          Button1.setSelected(false);
          Button2.setSelected(false);
          Button4.setSelected(false);
           radioText = Button3.getText();
                   }
             
                else
                {
                   if(Button4.isSelected())
                    {
          Button1.setSelected(false);
          Button2.setSelected(false);
          Button3.setSelected(false);  
           radioText = Button4.getText();
                  } 
                   else
                   {
                       radioText=" "; 
                   }
                }
              }
           }
       
        if(radioText.equals(Correct_Answer))
                 {
                   
                     //JOptionPane.showMessageDialog(rootPane,"correct answer");
                     number++;
                     System.out.println(number);
                        
               
                 } 
     
      else
      {
         // JOptionPane.showMessageDialog(rootPane," answer is not corect,Correct answer is "+a);
          // JOptionPane.showMessageDialog(rootPane,"correct answer is "+a);
         
            
      }
   //   radioText=" ";
      
       A.add(displaylist.get(i).getQuestion());
       B.add(displaylist.get(i).getCorrect());
       C.add(radioText);  
       
   i++;     
   Table();  
   
    
  
    }                                    

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        /*if(Button1.isSelected())
        {
          Button2.setSelected(false);
          Button3.setSelected(false);
          Button4.setSelected(false); 
            radioText = Button1.getText();
           
         
        }*/
        
    
    }                                       

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
       /*    if(Button2.isSelected())
        {
          Button1.setSelected(false);
          Button3.setSelected(false);
          Button4.setSelected(false); 
           radioText = Button2.getText();
        }*/
           
    }                                       

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
          /* if(Button3.isSelected())
        {
          Button1.setSelected(false);
          Button2.setSelected(false);
          Button4.setSelected(false);
           radioText = Button3.getText();
        }
         */
    
    }                                       

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
         /*  if(Button4.isSelected())
        {
          Button1.setSelected(false);
          Button2.setSelected(false);
          Button3.setSelected(false);  
           radioText = Button4.getText();
        }*/
          
    
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
      //  ArrayList<Display> displaylist=new ArrayList<Display>();
                
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuesDisplay().setVisible(true);
                
                
                
                
                
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton Button1;
    private javax.swing.JRadioButton Button2;
    private javax.swing.JRadioButton Button3;
    private javax.swing.JRadioButton Button4;
    private javax.swing.JButton Next;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
