/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class SIGNIN extends javax.swing.JFrame {
 String password;
 String name; 
    /**
     * Creates new form SIGNIN
     */
    
    public SIGNIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Signinbutton = new javax.swing.JToggleButton();
        Create = new javax.swing.JToggleButton();
        Cancel = new javax.swing.JToggleButton();
        UserPassword = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Passwordtextfield = new javax.swing.JPasswordField();
        Nametextfield = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Signinbutton.setBackground(new java.awt.Color(153, 51, 0));
        Signinbutton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Signinbutton.setText("SIGNIN");
        Signinbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigninbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Signinbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 180, 40));

        Create.setBackground(new java.awt.Color(153, 51, 0));
        Create.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Create.setText("CREATE AN ACCOUNT");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        jPanel1.add(Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, 40));

        Cancel.setBackground(new java.awt.Color(153, 51, 0));
        Cancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Cancel.setText("CANCEL");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 140, 40));

        UserPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UserPassword.setForeground(new java.awt.Color(153, 51, 0));
        UserPassword.setText("Your Password");
        jPanel1.add(UserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 190, 60));

        Username.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Username.setForeground(new java.awt.Color(153, 51, 0));
        Username.setText("UserName");
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 150, 150, 30));
        jPanel1.add(Passwordtextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 300, 30));
        jPanel1.add(Nametextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 290, 32));

        jCheckBox1.setBackground(new java.awt.Color(255, 51, 51));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox1.setText("You are agree our all Terms and Conditions.");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\Final.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
         password=Passwordtextfield.getText();
        name=Nametextfield.getText();
    //    is_Valid_Password(password);
    if(name.trim().isEmpty())
    {
    JOptionPane.showMessageDialog(SIGNIN.this, "name is empty");
    }
   if(is_Valid_Password(password))
     {
    //JOptionPane.showMessageDialog(SignIn.this, "password is valid");
        Table();
       MainPage w=new MainPage();
         w.setVisible(true);
         dispose();
     }
   else
    {
      invalid_password(password);
     }    
   
    }                                      

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
         close();
    }                                      

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void SigninbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    public void invalid_password(String password)
  {
  int i2=8;  
			    int s1=password.length();  
				
			 if(s1<i2)
			   {
                JOptionPane.showMessageDialog(null,"A password must not have atleast eight(8) character \n Click OK  and try again .2","Wronge Pass",JOptionPane.ERROR_MESSAGE);
				//System.out.println("Password is not Valid ="+password);
			   }
                         else  
			 {
			
                             String s2=password;
			   //System.out.println(s2);
				 if(s2.matches("[0-9]+")&&s2.length()>8)
			        {
				       JOptionPane.showMessageDialog(null," A password only  consist of digit&& doesnot have any  character.It always conist of atleat Two character \n Click OK  and try again .2","Wronge Pass",JOptionPane.ERROR_MESSAGE);
				      // System.out.println("Password is not Valid ="+password);
			        } 
		        else 
			        {
				       JOptionPane.showMessageDialog(null," A password doesnot consist of any number or digit.It contain atleast two number \n Click OK  and try again .2","Wronge Pass",JOptionPane.ERROR_MESSAGE);
				     //   System.out.println("Password is not Valid ="+password);
			        }
                         }
  
  }
    
    
    
     public static boolean is_Valid_Password(String password)
    {
       int  PASSWORD_Length=8;
       if(password.length()<PASSWORD_Length)
		{
			return false;
		}
      else
		{
		   int charCount=0 ;
		   int  numCount=0;
		   for(int i=0;i<password.length();i++)
		     {
			    char ch=password.charAt(i);
				
				if(is_Numeric(ch))
				 {
				   numCount++;
				  }
	            else if(is_Letter(ch))
				 {
				   charCount++;
				  }
				else 
				 {
				   return false;
				  }
			   }
				return (charCount>=2&&numCount>=2);
		}
	}	
		
  public static boolean is_Letter(char ch)
    {
       ch=Character.toUpperCase(ch);
        return (ch>='A'&&ch<='Z');
	}
 public static boolean is_Numeric(char ch)
    {
		return (ch>='0'&&ch<='9');
	}
public void  Table()
{
   try
          {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                System.out.println("connected");
               Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","java");
                System.out.println("connected");
               
               // Statement stmt = con.createStatement();
               // ResultSet rs =stmt.executeQuery("select*from STUDENT");
                
      /*  while(rs.next())
                    System.out.println(rs.getInt(1)+" "+rs.getString(2)+" "+rs.getString(3)+" "+rs.getString(4));*/
            String str="INSERT INTO SIGNIN1(USERNAME,PASSWORD)VALUES(?,?)";
             PreparedStatement ps=con.prepareStatement(str);
            
            ps.setString(1, name);
            ps.setString(2, password);
            
            
            int ri= ps.executeUpdate();
             if(ri>0){
             System.out.println("inserted");
             }
               // ps.setString(parameterIndex, str);
             
           }
        catch(Exception e)
            {
                System.out.println(e);
            }  
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGNIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGNIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGNIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGNIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGNIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton Cancel;
    private javax.swing.JToggleButton Create;
    private javax.swing.JTextField Nametextfield;
    private javax.swing.JPasswordField Passwordtextfield;
    private javax.swing.JToggleButton Signinbutton;
    private javax.swing.JLabel UserPassword;
    private javax.swing.JLabel Username;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   

   private void close()
{
    WindowEvent winclosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclosing);


}
}
