/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import static javaapplication4.MainPage.cat;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class NewJFrame extends javax.swing.JFrame {
    String s1,s,radioText;
public static ArrayList A=new ArrayList();      
public static ArrayList B=new ArrayList(); 
public static ArrayList C=new ArrayList(); 
public static String Currect_Question,Select_Answer,Correct_Answer;
int i=0;
public static int m;
public static int number=0;
ResultSet rs;
ArrayList<Display> displaylist=new ArrayList<Display>();
 public void Table()
      {
          
      if(i<=m)
      {
      
      //  System.out.print(i+"  "+m);
           // System.out.println(displaylist.get(i).getQuestion());
             
               jLabel2.setText(displaylist.get(i).getQuestion());
                jLabel5.setText(displaylist.get(i).getOption1());
                jLabel6.setText(displaylist.get(i).getOption2());
                jLabel7.setText(displaylist.get(i).getOption3());
                jLabel8.setText(displaylist.get(i).getOption4());
                jLabel9.setText(displaylist.get(i).getCorrect());
               // Correct_Answer=displaylist.get(i).getCorrect();
             //   Currect_Question=displaylist.get(i).getQuestion();
               // System.out.println(a);
                
               
                
                
              
      }    
     else
      {
           Result r=new Result();
          r.setVisible(true);
         dispose(); 
      }
     }

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        

    /**
     * Creates new form QuesDisplay
     */
       
  s=  MainPage.cat;
      System.out.println(s);
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            System.out.println("connected");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","SYSTEM","java");
            System.out.println("connected");
           
            System.out.println(cat); 
            
              String query="select * from QUEST WHERE CAT='"+cat+"'";
            PreparedStatement ps=con.prepareStatement(query);
                rs=ps.executeQuery();
     while(rs.next())
              {
                  m=displaylist.size();
                  Display d=new  Display();
                  d.setQuestion(rs.getString("QUES"));
                  d.setOption1(rs.getString("OP_1"));
                  d.setOption2(rs.getString("OP_2"));
                  d.setOption3(rs.getString("OP_3"));
                  d.setOption4(rs.getString("OP_4"));
                  d.setCorrect(rs.getString("CORRECT"));
                  // System.out.println(rs.getString("QUES"));
         Currect_Question=rs.getString("QUES");
                 // System.out.println(Currect_Question);
                  displaylist.add(d);
              
              
              }
     Table();
        
        } 
          catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e); 
        }
        finally{
            //Table();
        }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Next = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 600, 40);

        jLabel1.setBackground(new java.awt.Color(153, 51, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Correct _Answer:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 450, 210, 29);

        Next.setBackground(new java.awt.Color(204, 51, 0));
        Next.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        jPanel1.add(Next);
        Next.setBounds(380, 370, 170, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 180, 550, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 120, 520, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 330, 550, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(240, 440, 360, 40);

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(69, 370, 150, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 250, 550, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\Final.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 700, 520);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 610, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        i++;     
   Table(); 
    }                                    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        StartGame s=new StartGame();
        s.setVisible(true);
        dispose();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Next;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
